# ASSIGNMENT=04
CHI-SQUARE TEST
## Association between Device Type and Customer Satisfaction

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from scipy.stats import chi2_contingency
from scipy import stats
import numpy as np

In [29]:
observed = np.array([[50, 70],
                     [80, 100],
                     [60, 90],
                     [30, 50],
                     [20, 50]])


In [30]:
data = {
    'Satisfaction': ['Very Satisfied', 'Satisfied', 'Neutral', 'Unsatisfied', 'Very Unsatisfied'],
    'Smart Thermostat': [50, 80, 60, 30, 20],
    'Smart Light': [70, 100, 90, 50, 50],
    'Total': [120, 180, 150, 80, 70]
}



In [31]:
data


{'Satisfaction': ['Very Satisfied',
  'Satisfied',
  'Neutral',
  'Unsatisfied',
  'Very Unsatisfied'],
 'Smart Thermostat': [50, 80, 60, 30, 20],
 'Smart Light': [70, 100, 90, 50, 50],
 'Total': [120, 180, 150, 80, 70]}

In [32]:
df=pd.DataFrame(data)
df

Satisfaction  Smart Thermostat  Smart Light  Total
0    Very Satisfied                50           70    120
1         Satisfied                80          100    180
2           Neutral                60           90    150
3       Unsatisfied                30           50     80
4  Very Unsatisfied                20           50     70

In [33]:
# Sum of the rows and columns to calculate the expected values
row_totals = observed.sum(axis=1)
col_totals = observed.sum(axis=0)
total = observed.sum()

In [36]:
row_totals

array([120, 180, 150,  80,  70])

In [37]:
col_totals

array([240, 360])

In [35]:
expected = np.outer(row_totals, col_totals) / total
expected



array([[ 48.,  72.],
       [ 72., 108.],
       [ 60.,  90.],
       [ 32.,  48.],
       [ 28.,  42.]])

In [38]:
# Calculate the Chi-Square statistic
chi_square_stat = ((observed - expected) ** 2 / expected).sum()


In [39]:
chi_square_stat

5.638227513227513

In [42]:

# Degrees of freedom (df) = (number of rows - 1) * (number of columns - 1)
dof = (observed.shape[0] - 1) * (observed.shape[1] - 1)



In [43]:
dof

4

In [45]:
# Determine the critical value using the Chi-Square distribution table
alpha = 0.05
critical_value = stats.chi2.ppf(1 - alpha, dof)



In [46]:
critical_value


9.487729036781154

In [48]:
# Make a decision
if chi_square_stat > critical_value:
    decision = "Reject the null hypothesis (H0). There is a significant association between the type of device and customer satisfaction."
else:
    decision = "Fail to reject the null hypothesis (H0). There is no significant association between the type of device and customer satisfaction."

# Print the results
print(f"Chi-Square Statistic: {chi_square_stat:.2f}")
print(f"Critical Value: {critical_value:.2f}")
print(f"Decision: {decision}")


Chi-Square Statistic: 5.64
Critical Value: 9.49
Decision: Fail to reject the null hypothesis (H0). There is no significant association between the type of device and customer satisfaction.


In [50]:
'''This output indicates that there is no significant association between the type of device and customer satisfaction at the 0.05 significance level.'''












'This output indicates that there is no significant association between the type of device and customer satisfaction at the 0.05 significance level.'